FROM node:18-alpine

WORKDIR /app/client

# Install pnpm
RUN npm install -g pnpm

# Copy only the package files
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --no-frozen-lockfile

# Copy the rest of your source code
COPY . .

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]
