name: 部署到SERVER

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh deploy dev frontend to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            unset DOCKER_HOST
            export DOCKER_HOST=unix:///var/run/docker.sock
            cd /mnt/disk1/goodweather/senior-memes-frontend
            docker compose -f docker-compose.dev.yml down
            git pull
            docker compose -f docker-compose.dev.yml up -d --build